### PR TITLE
add two algorithms:FaIE and CSSP

### PR DESCRIPTION
**Pull request by algorithmdog**

### CODE REVIEW

**Comment by hsuantien** [comment]
Thanks. I'll check soon. Given my busy status it may need to wait until more than a week, though.

**Comment by hsuantien** [comment]
@rustle1314: I merged the pull request directly. After merging I decide to polish the FaIE code significantly. Now the code is hopefully cleaner than your original version and is more consistent with other parts of the package. You may be interested in taking a look. I'll spend some time on CSSP later. Thanks again for the contribution.

**Comment by algorithmdog** [comment]
@Hsuan-Tien Lin

Thank you.Your reviews and modifications will help me to improve my
programming skills.

When you polish the CSSP code, please change the 10-th line "sum_p=0" to
"sum_p=sum(p)". It is a mistake.

Next, I will open a pull request, which makes the code to handle the large
scale sparse data input.

Best Wishes,
Li.L

**Comment by hsuantien** [comment]
@rustle1314: I cleaned up CSSP today as well. I find that your original probability assignment is different from what the paper says (you use sum of vk while the paper use length of vk). So I fixed it. I also changed to rejection-based sampling for easier implementation. Please feel free to check. Thanks.

**Pull request merged**
