### PR TITLE
 add two algorithms: FaIE and CSSP. Please read README.md for more infor...

### PR DESCRIPTION
**Pull request by algorithmdog**
Hi, hsuantien. I added two algorithms: FaIE and CSSP. You can read the readme for more information. ~_~.

### CODE REVIEW

**Comment by hsuantien** [comment]
I started reviewing your code. First question, could you consider implementing FaIE similar to CPLST, for instance, using ridgereg_hat instead of calculating the Delta matrix by yourself?

Thanks.

**Comment by algorithmdog** [comment]
OK, I would modify the code and create a new pull request.~_~

**Comment by hsuantien** [comment]
Thanks. Perhaps we do not need to close the pull request. You can just commit your further changes along with this pull request. Thanks.

**Comment by algorithmdog** [comment]
Hi, hsuantien. I am sorry for your waiting. I was a little busy these days. Now, I am modifying my code and have some problems. 1) for the cplst encode function [Z, Zt, Vm, shift] = cplst_encode(Y, Yt, M, X, lambda). Why we need calculate the Zt. If I didn't misunderstand, Zt is the codes in the latent space for the test set. 2) What doesn't Vm stand for? I know it involves the recover matrix. Thank you in advance.

**Comment by hsuantien** [comment]
Thanks. That's a good question. The Zt was there for a historical reason while I agree that it should not be needed anymore. I'll work on a new branch to remove those when time allows (similarly super busy here).

Vm stands for the linear transform from Yshift to Z (Z = Yshift \* Vm, basically).

Thanks.

**Comment by algorithmdog** [comment]
Hi, hsuantien. I have completed the modification of the code. I create a new pull request and close this request for 2 reasons, namely, 1) I am not familiar with the github and don't know how to commit the further changes in the existing pull request, and 2) committing the further changes in the existing pull request will add some unnecessary comments to the master.

**Pull request closed without merging**
